name: Java CI Automation

# Kích hoạt khi có sự kiện push và pull_request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] # Báo cho GitHub biết: "Hãy chạy mỗi khi có PR hướng vào nhánh main"

permissions:
  contents: read
  pull-requests: write # quyền này để Bot được phép comment vào PR
  checks: write

jobs:
  build:
    # Cấu hình máy ảo thực thi
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Giúp máy Mac/Windows vẫn chạy nếu Ubuntu bị lỗi
      matrix:
        # Định nghĩa 3 hệ điều hành sẽ chạy song song
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cài đặt JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Giữ lại thư viện Maven đã tải để dùng lại cho các lần build sau
      # Bot review
      - name: Automated Code Review (Checkstyle Bot)
        if: github.event_name == 'pull_request' && runner.os == 'Linux'
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          filter_mode: nofilter
          checkstyle_config: google

      # Thực thi vòng đời Maven
      - name: Build, Test và Check Coverage với Maven
        if: always() # luôn chạy dù Bot tìm thấy lỗi
        run: mvn clean verify

      # Triển khai action upload-artifact để lưu giữ tệp .jar
      - name: Lưu trữ file JAR
        uses: actions/upload-artifact@v4
        with:
          name: bank-system-executable
          path: target/*.jar

      # Tải báo cáo HTML của JaCoCo lên GitHub
      - name: Lưu trữ báo cáo JaCoCo Code Coverage
        uses: actions/upload-artifact@v4
        if: always() # Luôn lấy báo cáo về kể cả khi bị Đỏ (fail do ko đủ 80%)
        with:
          name: jacoco-report-${{ matrix.os }}
          path: target/site/jacoco/